"""complete plate mvp schema

Revision ID: 88e1ca936693
Revises: 20260721_0001
Create Date: 2026-07-21 16:42:51.987858
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "88e1ca936693"
down_revision: str | None = "20260721_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "camera_configs",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("camera_code", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "roi_config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("default_sample_rate", sa.Float(), server_default="4.0", nullable=False),
        sa.Column("face_threshold", sa.Float(), server_default="0.5", nullable=False),
        sa.Column("plate_threshold", sa.Float(), server_default="0.5", nullable=False),
        sa.Column(
            "tracking_config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("jsonb_typeof(roi_config) = 'object'", name="ck_camera_roi_object"),
        sa.CheckConstraint(
            "jsonb_typeof(tracking_config) = 'object'", name="ck_camera_tracking_object"
        ),
        sa.CheckConstraint("default_sample_rate > 0", name="ck_camera_sample_rate_positive"),
        sa.CheckConstraint("face_threshold BETWEEN 0 AND 1", name="ck_camera_face_threshold_range"),
        sa.CheckConstraint(
            "plate_threshold BETWEEN 0 AND 1", name="ck_camera_plate_threshold_range"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("camera_code"),
    )
    op.create_table(
        "model_versions",
        sa.Column("model_type", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("runtime", sa.String(length=32), server_default="ONNX", nullable=False),
        sa.Column("file_path", sa.String(length=1024), nullable=True),
        sa.Column("file_sha256", sa.String(length=64), nullable=True),
        sa.Column(
            "config", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint("jsonb_typeof(config) = 'object'", name="ck_model_config_object"),
        sa.CheckConstraint(
            "model_type IN ('PLATE_DETECTOR', 'PLATE_OCR', 'PLATE_TRACKER', "
            "'FACE_DETECTOR', 'FACE_RECOGNIZER', 'FACE_TRACKER')",
            name="ck_model_type",
        ),
        sa.CheckConstraint(
            "file_sha256 IS NULL OR length(file_sha256) = 64", name="ck_model_sha256_length"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("model_type", "name", "version", name="uq_model_identity"),
    )
    op.create_table(
        "users",
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=32), server_default="ANNOTATOR", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint("role IN ('ADMIN', 'ANNOTATOR', 'REVIEWER')", name="ck_users_role"),
        sa.CheckConstraint("email = lower(email)", name="ck_users_email_lowercase"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "artifacts",
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("storage_key", sa.String(length=1024), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("mime_type", sa.String(length=127), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("frame_number", sa.BigInteger(), nullable=True),
        sa.Column("pts", sa.BigInteger(), nullable=True),
        sa.Column("timestamp_ms", sa.BigInteger(), nullable=True),
        sa.Column(
            "metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint("jsonb_typeof(metadata) = 'object'", name="ck_artifact_metadata_object"),
        sa.CheckConstraint(
            "kind IN ('SOURCE_VIDEO', 'SOURCE_IMAGE', 'FULL_FRAME', 'PLATE_CROP', "
            "'THUMBNAIL', 'EXPORT_XLSX', 'EXPORT_CSV', 'EXPORT_ZIP', 'LOG')",
            name="ck_artifact_kind",
        ),
        sa.CheckConstraint(
            "frame_number IS NULL OR frame_number >= 0", name="ck_artifact_frame_nonnegative"
        ),
        sa.CheckConstraint(
            "sha256 IS NULL OR length(sha256) = 64", name="ck_artifact_sha256_length"
        ),
        sa.CheckConstraint("size_bytes >= 0", name="ck_artifact_size_nonnegative"),
        sa.CheckConstraint(
            "timestamp_ms IS NULL OR timestamp_ms >= 0", name="ck_artifact_time_nonnegative"
        ),
        sa.ForeignKeyConstraint(["job_id"], ["processing_jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id", "id", name="uq_artifacts_job_id_id"),
        sa.UniqueConstraint("job_id", "storage_key", name="uq_artifact_job_storage_key"),
    )
    op.create_index("ix_artifacts_job_kind", "artifacts", ["job_id", "kind"], unique=False)
    op.create_index("ix_artifacts_sha256", "artifacts", ["sha256"], unique=False)
    op.create_table(
        "job_events",
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("level", sa.String(length=16), server_default="INFO", nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "data", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint("jsonb_typeof(data) = 'object'", name="ck_job_events_data_object"),
        sa.CheckConstraint(
            "level IN ('DEBUG', 'INFO', 'WARNING', 'ERROR')", name="ck_job_events_level"
        ),
        sa.ForeignKeyConstraint(["job_id"], ["processing_jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_job_events_job_created", "job_events", ["job_id", "created_at"], unique=False
    )
    op.create_table(
        "job_models",
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("model_version_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("role IN ('DETECTOR', 'OCR', 'TRACKER')", name="ck_job_model_role"),
        sa.ForeignKeyConstraint(["job_id"], ["processing_jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["model_version_id"], ["model_versions.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("job_id", "model_version_id"),
        sa.UniqueConstraint("job_id", "role", name="uq_job_model_role"),
    )
    op.create_table(
        "tracks",
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("track_code", sa.String(length=64), nullable=False),
        sa.Column("object_type", sa.String(length=16), server_default="PLATE", nullable=False),
        sa.Column("start_frame", sa.BigInteger(), nullable=False),
        sa.Column("end_frame", sa.BigInteger(), nullable=False),
        sa.Column("start_timestamp_ms", sa.BigInteger(), nullable=False),
        sa.Column("end_timestamp_ms", sa.BigInteger(), nullable=False),
        sa.Column("quality_score", sa.Float(), nullable=True),
        sa.Column("classification", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=32), server_default="OPEN", nullable=False),
        sa.Column(
            "evidence_status", sa.String(length=16), server_default="PENDING", nullable=False
        ),
        sa.Column("duplicate_of_id", sa.UUID(), nullable=True),
        sa.Column("event_key", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "evidence_status IN ('PENDING', 'VALID', 'INVALID')", name="ck_tracks_evidence_status"
        ),
        sa.CheckConstraint("object_type IN ('PLATE', 'FACE')", name="ck_tracks_object_type"),
        sa.CheckConstraint(
            "status IN ('OPEN', 'CLOSED', 'READY_FOR_REVIEW', 'DISCARDED')", name="ck_tracks_status"
        ),
        sa.CheckConstraint(
            "duplicate_of_id IS NULL OR duplicate_of_id <> id", name="ck_tracks_not_self_duplicate"
        ),
        sa.CheckConstraint("length(event_key) = 64", name="ck_tracks_event_key_length"),
        sa.CheckConstraint(
            "quality_score IS NULL OR quality_score BETWEEN 0 AND 1", name="ck_tracks_quality_range"
        ),
        sa.CheckConstraint(
            "start_frame >= 0 AND end_frame >= start_frame", name="ck_tracks_frame_range"
        ),
        sa.CheckConstraint(
            "start_timestamp_ms >= 0 AND end_timestamp_ms >= start_timestamp_ms",
            name="ck_tracks_time_range",
        ),
        sa.ForeignKeyConstraint(
            ["job_id", "duplicate_of_id"],
            ["tracks.job_id", "tracks.id"],
            name="fk_tracks_duplicate_same_job",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["job_id"], ["processing_jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id", "event_key", name="uq_tracks_job_event_key"),
        sa.UniqueConstraint("job_id", "id", name="uq_tracks_job_id_id"),
        sa.UniqueConstraint("job_id", "track_code", name="uq_tracks_job_track_code"),
    )
    op.create_index(
        "ix_tracks_job_start_time", "tracks", ["job_id", "start_timestamp_ms"], unique=False
    )
    op.create_index("ix_tracks_job_status", "tracks", ["job_id", "status"], unique=False)
    op.create_table(
        "detections",
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("track_id", sa.UUID(), nullable=True),
        sa.Column("object_type", sa.String(length=16), server_default="PLATE", nullable=False),
        sa.Column("source", sa.String(length=16), server_default="MODEL", nullable=False),
        sa.Column("frame_number", sa.BigInteger(), nullable=False),
        sa.Column("pts", sa.BigInteger(), nullable=True),
        sa.Column("timestamp_ms", sa.BigInteger(), nullable=False),
        sa.Column("bbox_x1", sa.Integer(), nullable=False),
        sa.Column("bbox_y1", sa.Integer(), nullable=False),
        sa.Column("bbox_x2", sa.Integer(), nullable=False),
        sa.Column("bbox_y2", sa.Integer(), nullable=False),
        sa.Column("detection_confidence", sa.Float(), nullable=False),
        sa.Column("quality_score", sa.Float(), nullable=True),
        sa.Column("is_best", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "evidence_status", sa.String(length=16), server_default="PENDING", nullable=False
        ),
        sa.Column("full_frame_artifact_id", sa.UUID(), nullable=False),
        sa.Column("crop_artifact_id", sa.UUID(), nullable=False),
        sa.Column("model_version_id", sa.UUID(), nullable=True),
        sa.Column(
            "raw_output",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "evidence_status IN ('PENDING', 'VALID', 'INVALID')",
            name="ck_detections_evidence_status",
        ),
        sa.CheckConstraint("jsonb_typeof(raw_output) = 'object'", name="ck_detection_raw_object"),
        sa.CheckConstraint("object_type IN ('PLATE', 'FACE')", name="ck_detections_object_type"),
        sa.CheckConstraint("source IN ('MODEL', 'MANUAL')", name="ck_detections_source"),
        sa.CheckConstraint(
            "bbox_x1 >= 0 AND bbox_y1 >= 0 AND bbox_x2 > bbox_x1 AND bbox_y2 > bbox_y1",
            name="ck_detections_bbox_valid",
        ),
        sa.CheckConstraint(
            "detection_confidence BETWEEN 0 AND 1", name="ck_detections_confidence_range"
        ),
        sa.CheckConstraint("frame_number >= 0", name="ck_detections_frame_nonnegative"),
        sa.CheckConstraint(
            "quality_score IS NULL OR quality_score BETWEEN 0 AND 1",
            name="ck_detections_quality_range",
        ),
        sa.CheckConstraint("timestamp_ms >= 0", name="ck_detections_time_nonnegative"),
        sa.ForeignKeyConstraint(
            ["job_id", "crop_artifact_id"],
            ["artifacts.job_id", "artifacts.id"],
            name="fk_detections_crop_same_job",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["job_id", "full_frame_artifact_id"],
            ["artifacts.job_id", "artifacts.id"],
            name="fk_detections_full_frame_same_job",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["job_id", "track_id"],
            ["tracks.job_id", "tracks.id"],
            name="fk_detections_track_same_job",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["job_id"], ["processing_jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["model_version_id"], ["model_versions.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id", "id", name="uq_detections_job_id_id"),
    )
    op.create_index(
        "ix_detections_job_frame", "detections", ["job_id", "frame_number"], unique=False
    )
    op.create_index("ix_detections_track", "detections", ["track_id"], unique=False)
    op.create_index(
        "uq_detections_one_best_per_track",
        "detections",
        ["track_id"],
        unique=True,
        postgresql_where=sa.text("is_best = true"),
    )
    op.create_table(
        "exports",
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("export_type", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="PENDING", nullable=False),
        sa.Column("artifact_id", sa.UUID(), nullable=True),
        sa.Column("record_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "config_snapshot",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("error_message", sa.String(length=1024), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "export_type IN ('GT_DRAFT', 'GT_FINAL', 'SUMMARY', 'CROP_ZIP')", name="ck_exports_type"
        ),
        sa.CheckConstraint(
            "jsonb_typeof(config_snapshot) = 'object'", name="ck_export_config_object"
        ),
        sa.CheckConstraint(
            "status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')", name="ck_exports_status"
        ),
        sa.CheckConstraint("record_count >= 0", name="ck_exports_record_count_nonnegative"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["job_id", "artifact_id"],
            ["artifacts.job_id", "artifacts.id"],
            name="fk_exports_artifact_same_job",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["job_id"], ["processing_jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("artifact_id"),
    )
    op.create_index("ix_exports_job_created", "exports", ["job_id", "created_at"], unique=False)
    op.create_table(
        "ground_truth_records",
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("track_id", sa.UUID(), nullable=False),
        sa.Column("selected_detection_id", sa.UUID(), nullable=False),
        sa.Column("record_code", sa.String(length=64), nullable=False),
        sa.Column("record_source", sa.String(length=16), server_default="MODEL", nullable=False),
        sa.Column("predicted_text", sa.String(length=64), nullable=True),
        sa.Column("prediction_confidence", sa.Float(), nullable=True),
        sa.Column("gt_text", sa.String(length=64), nullable=True),
        sa.Column("normalized_gt_text", sa.String(length=64), nullable=True),
        sa.Column("classification", sa.String(length=64), nullable=True),
        sa.Column(
            "quality_flags",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "verify_status", sa.String(length=16), server_default="UNVERIFIED", nullable=False
        ),
        sa.Column(
            "evidence_status", sa.String(length=16), server_default="PENDING", nullable=False
        ),
        sa.Column("is_duplicate", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("duplicate_of_id", sa.UUID(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("verified_by", sa.UUID(), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "evidence_status IN ('PENDING', 'VALID', 'INVALID')", name="ck_gt_evidence_status"
        ),
        sa.CheckConstraint(
            "jsonb_typeof(quality_flags) = 'array'", name="ck_gt_quality_flags_array"
        ),
        sa.CheckConstraint("record_source IN ('MODEL', 'MANUAL')", name="ck_gt_record_source"),
        sa.CheckConstraint(
            "verify_status <> 'VERIFIED' OR (normalized_gt_text IS NOT NULL "
            "AND evidence_status = 'VALID' AND verified_by IS NOT NULL "
            "AND verified_at IS NOT NULL)",
            name="ck_gt_verified_complete",
        ),
        sa.CheckConstraint(
            "verify_status IN ('UNVERIFIED', 'IN_REVIEW', 'VERIFIED', 'DISCARDED')",
            name="ck_gt_verify_status",
        ),
        sa.CheckConstraint(
            "(is_duplicate = false AND duplicate_of_id IS NULL) OR "
            "(is_duplicate = true AND duplicate_of_id IS NOT NULL)",
            name="ck_gt_duplicate_consistent",
        ),
        sa.CheckConstraint(
            "duplicate_of_id IS NULL OR duplicate_of_id <> id", name="ck_gt_not_self_duplicate"
        ),
        sa.CheckConstraint(
            "prediction_confidence IS NULL OR prediction_confidence BETWEEN 0 AND 1",
            name="ck_gt_prediction_confidence_range",
        ),
        sa.CheckConstraint("version >= 1", name="ck_gt_version_positive"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["job_id", "duplicate_of_id"],
            ["ground_truth_records.job_id", "ground_truth_records.id"],
            name="fk_gt_duplicate_same_job",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["job_id", "selected_detection_id"],
            ["detections.job_id", "detections.id"],
            name="fk_gt_detection_same_job",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["job_id", "track_id"],
            ["tracks.job_id", "tracks.id"],
            name="fk_gt_track_same_job",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["job_id"], ["processing_jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["verified_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id", "id", name="uq_gt_job_id_id"),
        sa.UniqueConstraint("job_id", "record_code", name="uq_gt_job_record_code"),
        sa.UniqueConstraint("job_id", "track_id", name="uq_gt_one_record_per_track"),
    )
    op.create_index(
        "ix_gt_job_evidence_status",
        "ground_truth_records",
        ["job_id", "evidence_status"],
        unique=False,
    )
    op.create_index(
        "ix_gt_job_verify_status", "ground_truth_records", ["job_id", "verify_status"], unique=False
    )
    op.create_table(
        "recognition_results",
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("track_id", sa.UUID(), nullable=True),
        sa.Column("detection_id", sa.UUID(), nullable=True),
        sa.Column("stage", sa.String(length=16), nullable=False),
        sa.Column("predicted_text", sa.String(length=64), nullable=False),
        sa.Column("normalized_text", sa.String(length=64), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("model_version_id", sa.UUID(), nullable=False),
        sa.Column(
            "candidates",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "raw_output",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "jsonb_typeof(candidates) = 'array'", name="ck_recognition_candidates_array"
        ),
        sa.CheckConstraint("jsonb_typeof(raw_output) = 'object'", name="ck_recognition_raw_object"),
        sa.CheckConstraint("stage IN ('FRAME_OCR', 'TRACK_VOTE')", name="ck_recognition_stage"),
        sa.CheckConstraint("confidence BETWEEN 0 AND 1", name="ck_recognition_confidence_range"),
        sa.CheckConstraint(
            "track_id IS NOT NULL OR detection_id IS NOT NULL", name="ck_recognition_has_parent"
        ),
        sa.ForeignKeyConstraint(
            ["job_id", "detection_id"],
            ["detections.job_id", "detections.id"],
            name="fk_recognition_detection_same_job",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["job_id", "track_id"],
            ["tracks.job_id", "tracks.id"],
            name="fk_recognition_track_same_job",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["job_id"], ["processing_jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["model_version_id"], ["model_versions.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_recognition_track_created",
        "recognition_results",
        ["track_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "review_actions",
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("ground_truth_record_id", sa.UUID(), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column(
            "before_state",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "after_state",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "action IN ('CREATE', 'EDIT', 'VERIFY', 'DISCARD', 'RESTORE', "
            "'MARK_DUPLICATE', 'UNMARK_DUPLICATE')",
            name="ck_review_action",
        ),
        sa.CheckConstraint("jsonb_typeof(after_state) = 'object'", name="ck_review_after_object"),
        sa.CheckConstraint("jsonb_typeof(before_state) = 'object'", name="ck_review_before_object"),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["job_id", "ground_truth_record_id"],
            ["ground_truth_records.job_id", "ground_truth_records.id"],
            name="fk_review_gt_same_job",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["job_id"], ["processing_jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_review_gt_created",
        "review_actions",
        ["ground_truth_record_id", "created_at"],
        unique=False,
    )
    op.add_column(
        "processing_jobs",
        sa.Column("source_type", sa.String(length=16), server_default="VIDEO", nullable=False),
    )
    op.add_column("processing_jobs", sa.Column("source_size_bytes", sa.BigInteger(), nullable=True))
    op.add_column(
        "processing_jobs", sa.Column("source_mime_type", sa.String(length=127), nullable=True)
    )
    op.add_column("processing_jobs", sa.Column("camera_config_id", sa.UUID(), nullable=True))
    op.add_column("processing_jobs", sa.Column("created_by", sa.UUID(), nullable=True))
    op.add_column(
        "processing_jobs",
        sa.Column(
            "processing_mode", sa.String(length=16), server_default="HIGH_RECALL", nullable=False
        ),
    )
    op.add_column(
        "processing_jobs",
        sa.Column("sample_rate", sa.Float(), server_default="4.0", nullable=False),
    )
    op.add_column(
        "processing_jobs", sa.Column("current_stage", sa.String(length=64), nullable=True)
    )
    op.add_column("processing_jobs", sa.Column("duration_ms", sa.BigInteger(), nullable=True))
    op.add_column("processing_jobs", sa.Column("width", sa.Integer(), nullable=True))
    op.add_column("processing_jobs", sa.Column("height", sa.Integer(), nullable=True))
    op.add_column("processing_jobs", sa.Column("fps", sa.Float(), nullable=True))
    op.add_column("processing_jobs", sa.Column("codec", sa.String(length=64), nullable=True))
    op.add_column("processing_jobs", sa.Column("time_base", sa.String(length=32), nullable=True))
    op.add_column(
        "processing_jobs", sa.Column("is_variable_frame_rate", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "processing_jobs", sa.Column("progress", sa.Float(), server_default="0.0", nullable=False)
    )
    op.add_column(
        "processing_jobs", sa.Column("pipeline_version", sa.String(length=64), nullable=True)
    )
    op.add_column("processing_jobs", sa.Column("git_commit", sa.String(length=64), nullable=True))
    op.add_column(
        "processing_jobs", sa.Column("container_digest", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "processing_jobs",
        sa.Column(
            "config_snapshot",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
    )
    op.add_column("processing_jobs", sa.Column("config_hash", sa.String(length=64), nullable=True))
    op.add_column(
        "processing_jobs", sa.Column("started_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "processing_jobs", sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "processing_jobs",
        sa.Column("cancel_requested_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column("processing_jobs", sa.Column("error_code", sa.String(length=64), nullable=True))
    op.add_column("processing_jobs", sa.Column("error_message", sa.Text(), nullable=True))
    op.create_check_constraint(
        "ck_processing_jobs_status",
        "processing_jobs",
        "status IN ('DRAFT', 'PENDING', 'QUEUED', 'PROCESSING', "
        "'WAITING_FOR_REVIEW', 'COMPLETED', 'FAILED', 'CANCELLED')",
    )
    op.create_check_constraint(
        "ck_jobs_object_mode",
        "processing_jobs",
        "object_mode IN ('PLATE', 'FACE', 'BOTH')",
    )
    op.create_check_constraint(
        "ck_jobs_processing_mode",
        "processing_jobs",
        "processing_mode IN ('HIGH_RECALL', 'BALANCED', 'FAST')",
    )
    op.create_check_constraint("ck_jobs_sample_rate_positive", "processing_jobs", "sample_rate > 0")
    op.create_check_constraint(
        "ck_jobs_progress_range", "processing_jobs", "progress BETWEEN 0 AND 100"
    )
    op.create_check_constraint(
        "ck_jobs_frame_counts_nonnegative",
        "processing_jobs",
        "processed_frames >= 0 AND (total_frames IS NULL OR total_frames >= 0)",
    )
    op.create_check_constraint(
        "ck_jobs_source_hash_length",
        "processing_jobs",
        "source_hash IS NULL OR length(source_hash) = 64",
    )
    op.create_check_constraint(
        "ck_jobs_config_hash_length",
        "processing_jobs",
        "config_hash IS NULL OR length(config_hash) = 64",
    )
    op.create_check_constraint(
        "ck_jobs_config_snapshot_object",
        "processing_jobs",
        "jsonb_typeof(config_snapshot) = 'object'",
    )
    op.create_check_constraint(
        "ck_jobs_source_type", "processing_jobs", "source_type IN ('VIDEO', 'IMAGE_SET')"
    )
    op.create_check_constraint(
        "ck_jobs_source_size_nonnegative",
        "processing_jobs",
        "source_size_bytes IS NULL OR source_size_bytes >= 0",
    )
    op.create_check_constraint(
        "ck_jobs_duration_nonnegative",
        "processing_jobs",
        "duration_ms IS NULL OR duration_ms >= 0",
    )
    op.create_check_constraint(
        "ck_jobs_dimensions_valid",
        "processing_jobs",
        "(width IS NULL AND height IS NULL) OR (width > 0 AND height > 0)",
    )
    op.create_check_constraint("ck_jobs_fps_positive", "processing_jobs", "fps IS NULL OR fps > 0")
    op.drop_index(op.f("ix_processing_jobs_job_code"), table_name="processing_jobs")
    op.create_index(
        "ix_processing_jobs_created_at", "processing_jobs", ["created_at"], unique=False
    )
    op.create_index(
        "ix_processing_jobs_source_hash", "processing_jobs", ["source_hash"], unique=False
    )
    op.create_foreign_key(
        "fk_jobs_created_by",
        "processing_jobs",
        "users",
        ["created_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "fk_jobs_camera_config",
        "processing_jobs",
        "camera_configs",
        ["camera_config_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_jobs_camera_config", "processing_jobs", type_="foreignkey")
    op.drop_constraint("fk_jobs_created_by", "processing_jobs", type_="foreignkey")
    op.drop_constraint("ck_jobs_fps_positive", "processing_jobs", type_="check")
    op.drop_constraint("ck_jobs_dimensions_valid", "processing_jobs", type_="check")
    op.drop_constraint("ck_jobs_duration_nonnegative", "processing_jobs", type_="check")
    op.drop_constraint("ck_jobs_source_size_nonnegative", "processing_jobs", type_="check")
    op.drop_constraint("ck_jobs_source_type", "processing_jobs", type_="check")
    op.drop_constraint("ck_jobs_config_snapshot_object", "processing_jobs", type_="check")
    op.drop_constraint("ck_jobs_config_hash_length", "processing_jobs", type_="check")
    op.drop_constraint("ck_jobs_source_hash_length", "processing_jobs", type_="check")
    op.drop_constraint("ck_jobs_frame_counts_nonnegative", "processing_jobs", type_="check")
    op.drop_constraint("ck_jobs_progress_range", "processing_jobs", type_="check")
    op.drop_constraint("ck_jobs_sample_rate_positive", "processing_jobs", type_="check")
    op.drop_constraint("ck_jobs_processing_mode", "processing_jobs", type_="check")
    op.drop_constraint("ck_jobs_object_mode", "processing_jobs", type_="check")
    op.drop_constraint("ck_processing_jobs_status", "processing_jobs", type_="check")
    op.drop_index("ix_processing_jobs_source_hash", table_name="processing_jobs")
    op.drop_index("ix_processing_jobs_created_at", table_name="processing_jobs")
    op.create_index(
        op.f("ix_processing_jobs_job_code"), "processing_jobs", ["job_code"], unique=False
    )
    op.drop_column("processing_jobs", "error_message")
    op.drop_column("processing_jobs", "error_code")
    op.drop_column("processing_jobs", "cancel_requested_at")
    op.drop_column("processing_jobs", "completed_at")
    op.drop_column("processing_jobs", "started_at")
    op.drop_column("processing_jobs", "config_hash")
    op.drop_column("processing_jobs", "config_snapshot")
    op.drop_column("processing_jobs", "container_digest")
    op.drop_column("processing_jobs", "git_commit")
    op.drop_column("processing_jobs", "pipeline_version")
    op.drop_column("processing_jobs", "progress")
    op.drop_column("processing_jobs", "is_variable_frame_rate")
    op.drop_column("processing_jobs", "time_base")
    op.drop_column("processing_jobs", "codec")
    op.drop_column("processing_jobs", "fps")
    op.drop_column("processing_jobs", "height")
    op.drop_column("processing_jobs", "width")
    op.drop_column("processing_jobs", "duration_ms")
    op.drop_column("processing_jobs", "current_stage")
    op.drop_column("processing_jobs", "sample_rate")
    op.drop_column("processing_jobs", "processing_mode")
    op.drop_column("processing_jobs", "created_by")
    op.drop_column("processing_jobs", "camera_config_id")
    op.drop_column("processing_jobs", "source_mime_type")
    op.drop_column("processing_jobs", "source_size_bytes")
    op.drop_column("processing_jobs", "source_type")
    op.drop_index("ix_review_gt_created", table_name="review_actions")
    op.drop_table("review_actions")
    op.drop_index("ix_recognition_track_created", table_name="recognition_results")
    op.drop_table("recognition_results")
    op.drop_index("ix_gt_job_verify_status", table_name="ground_truth_records")
    op.drop_index("ix_gt_job_evidence_status", table_name="ground_truth_records")
    op.drop_table("ground_truth_records")
    op.drop_index("ix_exports_job_created", table_name="exports")
    op.drop_table("exports")
    op.drop_index(
        "uq_detections_one_best_per_track",
        table_name="detections",
        postgresql_where=sa.text("is_best = true"),
    )
    op.drop_index("ix_detections_track", table_name="detections")
    op.drop_index("ix_detections_job_frame", table_name="detections")
    op.drop_table("detections")
    op.drop_index("ix_tracks_job_status", table_name="tracks")
    op.drop_index("ix_tracks_job_start_time", table_name="tracks")
    op.drop_table("tracks")
    op.drop_table("job_models")
    op.drop_index("ix_job_events_job_created", table_name="job_events")
    op.drop_table("job_events")
    op.drop_index("ix_artifacts_sha256", table_name="artifacts")
    op.drop_index("ix_artifacts_job_kind", table_name="artifacts")
    op.drop_table("artifacts")
    op.drop_table("users")
    op.drop_table("model_versions")
    op.drop_table("camera_configs")
    # ### end Alembic commands ###
